name: Generate OpenAPI Types

on:
  schedule:
    - cron: '0 4 * * *'  # every day at 4am UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI Types
        run: npm run generate-openapi-types

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
            token: ${{ secrets.requirements_bot_github_token }}
            commit-message: 'chore: generate Open API types'
            title: 'Generate Open API types'
            body: |
              This PR was automatically generated by the ``generate-openapi-types`` GitHub Action workflow.
              It updates the Open API types based on the latest API specifications in configured dependent services.
            branch: automation/generate-openapi-types
