name: Update Browserslist DB
on:
  schedule:
    - cron:  '0 0 * * 1'  # Schedule: Runs weekly at midnight on Mondays
  workflow_dispatch:

jobs:
  update-browserslist:
    uses: openedx/.github/.github/workflows/update-browserslist-db.yml@master

    secrets:
        requirements_bot_github_token: ${{ secrets.requirements_bot_github_token }}
